version: '3.8'

services:
  servico-clientes:
    build: .
    container_name: servico-clientes
    ports:
      - "8083:8083"
    depends_on:
      - mongodb-clientes
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-clientes:27017/clientesdb

  mongodb-clientes:
    image: mongo:6.0
    container_name: mongodb-clientes
    ports:
      - "27019:27017"
    volumes:
      - mongo_clientes_data:/data/db

volumes:
  mongo_clientes_data:
