version: '3.8'

services:
  loginjwt:
    build: .
    container_name: servico-loginjwt
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/loginjwt
      - DEMO_JWT_SECRET=segredo1234567890
      - DEMO_JWT_EXPIRATION=3600000

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
